# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# Config Verified https://rhysd.github.io/actionlint/

name: Vitest Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write
      
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install packages
        run: npm ci

      - name: Execute Coverage report
        id: coverage
        continue-on-error: true
        run: npm run test:coverage

      - name: label when coverage fails
        if: ${{ steps.coverage.outcome == 'failure' }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "commit-message-rule-violation"

      - name: label removal when coverage succeeds
        if: ${{ steps.coverage.outcome == 'success' }}
        uses: andymckay/labeler@1.0.4
        with:
          remove-labels: "commit-message-rule-violation"

      - name: Vitest Coverage Report
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2.1.1
        with:
          name: 'Frontend'
          json-summary-path: './coverage/coverage-summary.json'
          json-final-path: './coverage/coverage-final.json'
